services:
  postgres:
    image: postgres:alpine
    ports:
      - "${DB_PORT}:${DB_PORT}"
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
    volumes:
      - postgresql:/var/lib/postgresql/data

volumes:
  postgresql:
